### ISSUE TITLE
无法更改快捷键，即使加了更改快捷键的MOD也一样

### ISSUE THREAD

**Issue by 06ly6** [Enaium-StardewValleyMods/QuickShop#18]

**Comment by Enaium** [comment]
可以改啊

**Comment by 06ly6** [comment]
是我操作错了吗，我在UI改按键MOD网页那里没看到教程

**Comment by 06ly6** [comment]
是我操作错了吗我在网页那里没有看到教程，我是先这样，再这样的，如图
![1](https://github.com/user-attachments/assets/0a3b97ff-a36c-4755-ac46-5b7db45ac7ff)
![2](https://github.com/user-attachments/assets/9cb41e07-88b6-43a4-afd5-e10e480914e4)

**Comment by Enaium** [comment]
这个是模组设置，里面没有修改快捷键的

**Comment by Enaium** [comment]
用KeyBindUI或者直接改配置文件

**Comment by 06ly6** [comment]
不好意思，是我没有说清楚，我的意思是，我加了KeyBindUI，但是在3DM网页界面找不到KeyBindUI之前的教学了，导致我不清楚如何改绑定按键，所以麻烦您说明一下使用方法，或者发一下教程

**Comment by Enaium** [comment]
打开KeyBindUI里面会展示所有模组，找到QuickShop点进去就能操作了

**Comment by 06ly6** [comment]
那应该按什么快捷键打开，或者是在什么界面打开，我在游戏中点击KeyBindU没反应，在标题中KeyBindU设置也没反应(会在WIN命令栏那里出现红字)
![Uploading 屏幕截图 2024-07-16 105753.png…]()

**Comment by 06ly6** [comment]
![屏幕截图 2024-07-16 105753](https://github.com/user-attachments/assets/86ea93e9-78d5-410d-8a91-a49458cb29be)

**Comment by Enaium** [comment]
这也不这个mod的问题

**Comment by 06ly6** [comment]
那KeyBindUI的快捷键是啥，可能是我的操作问题，可能不是我那样打开的

**Comment by Enaium** [comment]
进入游戏，打开游戏菜单，从这里打开试试

**Comment by 06ly6** [comment]
试了，也是游戏没反应，WIN命令行那里有反应，我发一下截图

**Comment by 06ly6** [comment]
![屏幕截图 2024-07-16 111500](https://github.com/user-attachments/assets/1287e60f-630f-41ce-a460-b037bf05cfac)

**Comment by Enaium** [comment]
https://github.com/Enaium/sdv-mod-KeyBindUI/issues
